---
title: "Transects"
description: |
  Walked transects for mammals (and iguanas)
output:
    distill::distill_article:
      toc: true
      toc_depth: 3
---

80% of the work involved in this kind of fieldwork is just getting to the sampling points, so it makes sense to do as much as possible on a given trip. When we first visit points to collect metadata, we also deploy cameras, audiomoths, and sometimes collect soil at the same time. We try to time camera/audiomoth collection with other occasions when we need to visit points, like during bird point counts or Gentry transects. The goal is to visit each point the minimum number of times, and to collect as much data as possible every time.

This ethos led me to develop the mammal transect protocol. Field crews are equipped with Gaia GPS Pro apps on their phones, which help them navigate to sampling points. Gaia also gives accurate tracking information that can automatically be uploaded online. Each time the crew goes into the field, they are also running a mammal transect wherever they go. 